<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/style.css">
    <title>Cadastro</title>
</head>
<body>
    <div class="container">

    <div class="row">
            <div class="col-12 central pt-5">
                <h1 class="text-center">Cadastro</h1>
            </div>
        </div>

        <form method="post" action="/cadastroUsuario/">
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" name="email" id="inputEmail4" placeholder="Email">
    </div>
    <div class="form-group col-md-12">
      <label for="inputAddress">Nome</label>
      <input type="text" class="form-control" name="nome" id="inputAddress" placeholder="João da Silva">
    </div>
   
    <div class="form-group col-md-12">
      <label for="inputPassword4">Senha</label>
      <input type="password" class="form-control" name="senha" id="inputPassword4" placeholder="Senha">
    </div>

    
  </div>

  <button type="submit" class="btn btn-dark">Cadastrar</button>
</form>
    </div>
</body>
</html>