<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
     <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/css/style.css">
    <title>Cadastro</title>
</head>
<body>
    <div class="container">

    <div class="row">
            <div class="col-12 central pt-5">
                <h1 class="text-center">Cadastro de Jogadores</h1>
            </div>
        </div>

        <form method="post" action="/adicionarJogador/">
  <div class="form-row">

    <div class="form-group col-md-12">
      <label for="inputAddress">Nome do Jogador</label>
      <input type="text" class="form-control" required name="nome" id="inputAddress" placeholder="Ademir da Guia">
    </div>
    <div class="form-group col-md-12">
      <label for="inputAddress">Posição</label>
      <input type="text" class="form-control" required name="posicao" id="inputAddress" placeholder="Centro Avante">
    </div>
    <div class="form-group col-md-12">
      <label for="inputAddress">Número</label>
      <input type="number" class="form-control" required name="numero" id="inputAddress" placeholder="Número da Camiseta: 10!">
    </div>
   
    <div class="form-group col-md-12">
      <label for="inputAddress">Time do Jogador</label>
      <select name="timeID" id="">
        <option value="2">Flamengo</option>
        <option value="1">Grêmio</option>
      </select>
    </div>

    
  </div>

  <button type="submit" class="btn btn-dark">Cadastrar</button> 
</form>

    </div>
</body>
</html>