<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Perna de Pau | Login</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/style.css">
</head>

<body>
    <!--  -->
    <div class="container">
        <div class="row">
            <div class="col-12 central pt-5">
                <h1 class="text-center mr-5">Perna de Pau</h1>
            </div>
        </div>
        <div id="background" class="row mx-auto">
            <div class="col-12 mx-auto pt-5" id="goleiro">Goleiro</div>

        </div>
        </div>

    </div>
</body>

</html>